In [1]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [2]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

y = w * x + b

y.backward()

In [3]:
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [6]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

print('x : \n', x, '\n')
print('y : \n', y, '\n')

x : 
 tensor([[-0.3199,  0.6741, -1.2218],
        [-0.2186,  1.7770,  0.6082],
        [-0.1417,  0.4510,  1.0196],
        [ 0.5832,  0.6088,  0.5052],
        [-0.1822, -0.3973, -1.9413],
        [ 0.8348, -0.1701,  0.8357],
        [-0.8650, -1.2497, -1.5493],
        [ 1.3471, -1.0537,  1.1769],
        [-2.0931, -0.6460,  0.0594],
        [-0.6601,  0.1608,  0.3613]]) 

y : 
 tensor([[ 0.4895, -0.1647],
        [ 0.0590,  0.9889],
        [ 0.9463,  0.7961],
        [-1.4154, -1.2812],
        [-0.6857, -0.4789],
        [ 0.2296, -0.6366],
        [-0.1250, -0.2199],
        [-1.3699, -0.8379],
        [ 0.5114,  1.9680],
        [-0.6130,  0.8605]]) 



In [7]:
linear = nn.Linear(3, 2)
print('w :', linear.weight)
print('b :', linear.bias)

w : Parameter containing:
tensor([[-0.1484, -0.2857,  0.0766],
        [ 0.2834,  0.0773, -0.4624]], requires_grad=True)
b : Parameter containing:
tensor([ 0.5273, -0.5333], requires_grad=True)


In [9]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

pred = linear(x)

In [10]:
loss = criterion(pred, y)
print('loss : ', loss.item())

loss :  1.6178367137908936


In [12]:
# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[ 0.1190, -0.3358, -0.0068],
        [ 0.8632, -0.1999, -0.5084]])
dL/db:  tensor([ 0.7446, -0.6734])


In [13]:
optimizer.step()

pred=linear(x)
loss=criterion(pred,y)
print('loss after 1 step optimization: ',loss.item())

loss after 1 step optimization:  1.5961486101150513


In [14]:
# Create a numpy array.
x=np.array([[1,2], [3,4]])
# Convert the numpy array to a torch tensor.
y=torch.from_numpy(x)
# Convert the torch tensor to a numpy array.
z=y.numpy()


In [15]:
train_dataset=torchvision.datasets.CIFAR10(root='../../data/',
train=True,
transform=transforms.ToTensor(),
download=True)

100%|███████████████████████████████████████████████████████████████| 170498071/170498071 [00:36<00:00, 4716809.27it/s]


Extracting ../../data/cifar-10-python.tar.gz to ../../data/


In [16]:
image,label=train_dataset[0]
print(image.size())
print(label)


torch.Size([3, 32, 32])
6


In [17]:
# Data loader (this provides queues and threads in a very simple way).
train_loader=torch.utils.data.DataLoader(dataset=train_dataset,
batch_size=64,
shuffle=True)


In [20]:
# When iteration starts, queue and thread start to load data from files.
data_iter=iter(train_loader)
# Mini-batch images and labels.
images,labels=data_iter.__next__()


In [22]:
len(images)

64